FROM ubuntu:14.04

RUN apt-get update -q
RUN sudo apt-get install software-properties-common -y
RUN sudo add-apt-repository ppa:chris-lea/node.js -y
RUN apt-get update -q
RUN sudo apt-get install nodejs -y
